"use client";
import { useEffect, useRef, useState } from "react";
import { rightsCases, rightsLabels, rightsMilestones, rightsScreens, rightsSources, rightsTerms } from "./rights-data";
import "./rights-strand.css";

export function RightsEntry({href = "#rights"}:{href?:string}) {
  return <aside className="rights-entry"><div><small>RIGHTS · EQUALITY · VOICE</small><h2>Racism, Human Rights &amp; Freedom of Expression</h2><p>Explore disagreement, discrimination and what we can do. October foundations → November 20 children’s rights → December 10 human rights.</p></div><a href={href}>Open the inquiry →</a></aside>;
}

export default function RightsStrand({adult = false}:{adult?:boolean}) {
  const [section,setSection] = useState<"learn"|"scenarios"|"action">("learn");
  const [index,setIndex] = useState(0);
  const [selected,setSelected] = useState<number[]>([]);
  const [revealed,setRevealed] = useState(false);
  const [reason,setReason] = useState("");
  const [screen,setScreen] = useState(0);
  const [projecting,setProjecting] = useState(false);
  const projection = useRef<HTMLDialogElement>(null);
  const active = rightsCases[index];
  useEffect(()=>{if(projecting&&!projection.current?.open)projection.current?.showModal();},[projecting]);
  const closeProjector=()=>{projection.current?.close();setProjecting(false);};
  const chooseCase=(n:number)=>{setIndex(n);setSelected([]);setReason("");setRevealed(false);};
  return <section className="rights-strand" aria-labelledby="rights-title">
    <header className="rights-heading"><p className="rights-kicker">{adult?"K–7 · CANADA & BRITISH COLUMBIA":"GRADE 6 · RIGHTS & BELONGING"}</p><h1 id="rights-title">Racism, Human Rights<br/>&amp; Freedom of Expression</h1><p>When does freedom of expression protect what someone says, and when can expression interfere with another person’s rights?</p></header>
    <div className="rights-nav" role="group" aria-label="Choose inquiry section">{([["learn","1 · Learn"],["scenarios","2 · Where is the line?"],["action","3 · Take action"]] as const).map(([id,label])=><button key={id} aria-pressed={section===id} onClick={()=>setSection(id)}>{label}</button>)}</div>
    {section==="learn"&&<>
      <div className="rights-start"><div><h2>Start with “Can I disagree?”</h2><p>25 minutes · a partner, paper and pencil · no student device needed</p><p>Learn why expression matters, compare two statements, and explain one way to protect another person’s rights.</p></div><button onClick={()=>{setScreen(0);setProjecting(true);}}>Open four teaching screens</button></div>
      <div className="rights-four">{[
        ["01","Expression is a right","We can question rules, disagree and criticize people in power. An idea is not automatically illegal because someone finds it offensive."],
        ["02","Rights have limits","Some expression can threaten safety or interfere with others’ rights. Criminal law, human-rights law and school expectations answer different questions."],
        ["03","Racism is broader than crime","Racism can appear in words, actions and systems. Something can be harmful or discriminatory without being a criminal offence."],
        ["04","Adults have responsibilities too","Schools should protect students from discrimination and respect their right to be heard. Responses need evidence, fairness, support and follow-through."],
      ].map(([n,title,text])=><article key={n}><b>{n}</b><h2>{title}</h2><p>{text}</p></article>)}</div>
      <details className="rights-panel"><summary>Words we will use</summary><dl>{rightsTerms.map(([word,definition])=><div key={word}><dt>{word}</dt><dd>{definition}</dd></div>)}</dl></details>
      <section className="rights-panel"><h2>Two dates, one continuing inquiry</h2><p>These are planned learning milestones. Exact lesson days stay flexible.</p><ol className="rights-timeline">{rightsMilestones.map(m=><li key={m.when}><small>{m.when}</small><h3>{m.title}</h3><p>{m.detail}</p></li>)}</ol></section>
      {adult&&<>
        <details className="rights-panel"><summary>Teacher guide · three ready-to-teach sessions</summary><p><b>Prepare:</b> Read the source notes below, preview the nine cases, and choose examples suitable for your group. Have plain paper ready; print the response page only if useful.</p><ol>
          <li><b>Can I disagree? · 25 minutes.</b> Use the four teaching screens. Model the schedule example, read UNICEF articles 2, 12 and 13, compare criticism with exclusion, and collect the two-sentence exit response.</li>
          <li><b>Where Is the Line? · 35 minutes.</b> Revisit the four ideas (5). Model Petition (5): name the evidence, a missing fact and a response. Pairs investigate Accent, Club and Screenshot (15). Compare explanations rather than scores (5). Finish: “A category can overlap with another because…” (5).</li>
          <li><b>Rights in action · 35 minutes.</b> Read the council-access case (5). Connect it to children’s participation rights (5). Teams draft a proposal with the Take action template (15). Swap and test whether a child could follow it (5). Revise one unclear step and name an adult decision-maker (5).</li>
        </ol><p><b>Look for:</b> Distinguishes a policy from an identity; supports an interpretation with a scenario detail; names missing context; proposes a proportionate response; explains what an adult must do. No child needs to disclose personal experiences.</p><p><b>Next connections:</b> Freedom, Rules &amp; Power → Who Checks the People in Charge? → Whose Perspective Is Missing? Use evidence checks in Newsroom and the existing civic decision brief. This supports BC Grade 6 learning about government, rights, discrimination, perspectives and ethical responses; it is not a new required unit.</p></details>
        <details className="rights-panel"><summary>K–3 and Grades 4–7 adaptations</summary><h3>K–3 · everyone gets a voice · 15–20 minutes</h3><p>Read this fictional story: “A class chooses a new game. Only the loudest children get a turn to suggest one. Another child has an idea but needs more time.” Model: “We could wait and let children point, draw or tell us.” Children draw or act out one fair change. Finish by naming an adult who can help. Use no hate-speech labels or criminal sorting.</p><h3>Grades 4–5 · reasons and fairness</h3><p>Read Petition and Access aloud. Partners identify what happened and suggest a fair response. Supply the sentence frame: “I noticed __. This affects __. An adult could __.”</p><h3>Grades 6–7 · context and power</h3><p>Use the full case set selectively. Ask who makes a rule, who bears its effects and who can review it. Keep legal determinations with adults. Allow drawing, oral response, scribing or assistive communication.</p></details>
        <details className="rights-panel rights-adult"><summary>Adult background · law, school expectations and care</summary><h3>Keep three questions separate</h3><p><b>Charter:</b> Section 2(b) broadly protects expression against government restriction. Section 1 permits justified limits. Offensive content is not automatically excluded from protection. Disagreement alone does not justify arbitrary school punishment. “Free speech” and “freedom of expression” are not opposing Canadian and American rights.</p><p><b>Criminal law:</b> Section 319 addresses public incitement likely to cause a breach of the peace and wilful promotion of hatred outside private conversation, among other offences. Its current definition concerns extreme vilification and detestation; merely hurting, humiliating or offending is insufficient. Threats can engage other offences. These fictional cards cannot establish criminal liability.</p><p><b>BC human-rights law:</b> Section 7 addresses discriminatory publications, with specified grounds and exceptions for private communications. Section 8 addresses discrimination in public services. A complaint needs the relevant legal elements and context; not every unfair interaction falls under the Code. Its purposes include equal dignity, participation and reducing persistent inequality. Intent to discriminate is not always necessary.</p><p><b>School response:</b> Use the current school code and district procedures with an administrator. Protect safety, hear the accounts, explain decisions and use fair, proportionate support and consequences. The school can respond to harmful conduct without first establishing a crime. The linked Walnut Road page provides the school’s conduct documents; confirm the current version before using them for a specific incident.</p><h3>Respond without putting children on trial</h3><p>Stop identity-based harm, support the targeted child privately and document through school procedures. Do not debate whether a group deserves rights, reenact slurs, ask students to represent a community, or invite public accusations. Name racism, homophobia, antisemitism and Islamophobia accurately when supported by the facts. Students may pass; they can analyse a fictional case instead. Repair does not require a targeted child to forgive, educate others or meet the person who harmed them.</p><p>Get adult help for threats, repeated harassment, exclusion, fear or retaliation. Support need not wait for a final label. Protect expression that challenges injustice as well as participation free from discrimination.</p><p><small>Sources checked September 18, 2026. General educator background, not advice on deciding an individual legal case.</small></p></details>
      </>}
      <details className="rights-panel"><summary>Read the sources</summary><ul>{rightsSources.filter((_,i)=>adult||i>=4).map(s=><li key={s.href}><a href={s.href} target="_blank" rel="noreferrer">{s.label} ↗</a></li>)}</ul></details>
    </>}
    {section==="scenarios"&&<>
      <div className="rights-panel"><h2>Where Is the Line?</h2><p>Read one fictional situation. Select every category you can support, explain your evidence, then consider the discussion notes. There is no score: context can change the answer.</p><p>You can speak, draw or write instead of typing. Do not enter names or real incidents. Typed responses stay on this page only and clear when you change cases or leave.</p><label htmlFor="rights-case">Choose a situation</label><select id="rights-case" value={index} onChange={e=>chooseCase(Number(e.target.value))}>{rightsCases.map((c,i)=><option key={c.id} value={i}>{i+1}. {c.title}</option>)}</select></div>
      <article className="rights-case" aria-labelledby="rights-case-title"><small>FICTIONAL CASE {index+1} / {rightsCases.length}</small><h2 id="rights-case-title">{active.title}</h2><p className="rights-case-text">{active.text}</p><fieldset><legend>What might apply? Choose more than one if needed.</legend>{rightsLabels.map((label,i)=><label key={label}><input type="checkbox" checked={selected.includes(i)} onChange={()=>setSelected(s=>s.includes(i)?s.filter(n=>n!==i):[...s,i])}/>{label}</label>)}</fieldset><label htmlFor="rights-reason">What detail supports your thinking? What else do you need to know?</label><textarea id="rights-reason" rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="I notice… I would need to know…"/><button aria-expanded={revealed} onClick={()=>setRevealed(v=>!v)}>{revealed?"Hide discussion notes":"Compare with discussion notes"}</button>
      {revealed&&<div className="rights-feedback"><h3>One supported reading</h3><p><b>{active.tags.map(i=>rightsLabels[i]).join(" + ")}</b></p><p>{active.reason}</p><h3>What information matters?</h3><p>{active.missing}</p><h3>A helpful next step</h3><p>{active.action}</p></div>}
      <div className="rights-controls"><button disabled={index===0} onClick={()=>chooseCase(index-1)}>← Previous case</button><button disabled={index===rightsCases.length-1} onClick={()=>chooseCase(index+1)}>Next case →</button><button onClick={()=>window.print()}>Print this case &amp; response page</button></div></article>
      <p className="rights-note">Possible criminal hate speech belongs in adult assessment. If someone may be in danger, get help immediately; you do not need to decide which law applies.</p>
    </>}
    {section==="action"&&<>
      <section className="rights-panel"><small>LEADERSHIP &amp; SPIRIT CLUB</small><h2>Rights, Respect &amp; Responsibility</h2><p>Help other students understand a right, practise a response and know when to ask an adult for help.</p><p><b>School-year pathway:</b> Begin with the club’s October 21 launch; develop through November 20 and revisit for December 10. Schools using this resource can choose their own meeting dates.</p><ol className="rights-timeline">
      <li><h3>1. Investigate · first meeting</h3><p>Try two fictional cases. Use UNICEF articles 2, 12 and 13 to identify a right. Ask: who can use it easily, who faces a barrier, and what must adults do?</p></li>
      <li><h3>2. Choose one useful change</h3><p>Choose one school routine, such as sharing ideas at class council. Invite voluntary feedback about that routine without collecting personal incidents or names. Decide what your project should help students do.</p></li>
      <li><h3>3. Make and test · before November 20</h3><p>Create a scenario card, a 30-second announcement, a hallway infographic or a five-minute class activity. Include one right, a fictional example, a safe response and an adult-help step. Have your sponsor check accuracy and care, then trial it with a small group.</p></li>
      <li><h3>4. Share and improve · November 20</h3><p>Ask your sponsor to arrange sharing. Collect anonymous, non-personal feedback: “What could you do next?” Count whether the response was understandable, not how many students have experienced discrimination.</p></li>
      <li><h3>5. Connect and report back · December 10</h3><p>Add the wider human-rights connection. Show what feedback changed. Ask the relevant adult to explain what action was taken on your proposal. Revisit the change before winter break.</p></li></ol></section>
      <section className="rights-panel"><h2>A model students can adapt</h2><p><b>Right:</b> Children should have a meaningful way to share views on decisions affecting them.</p><p><b>Situation:</b> Class council hears only fast spoken answers.</p><p><b>Proposal:</b> Accept drawings, written suggestions and communication-device contributions, and allow thinking time.</p><p><b>Adult responsibility:</b> The teacher arranges access, considers the ideas and explains the decision.</p><p><b>Check:</b> After two meetings, ask anonymously whether students understood the options and could use a suitable one. Revise with adult help.</p></section>
      <section className="rights-panel"><h2>Your finished proposal</h2><ol><li>Name the right and source.</li><li>Describe the fictional situation or school routine.</li><li>Explain who faces a barrier without naming students.</li><li>Propose one practical change and an adult who can approve it.</li><li>Choose a way to share, test and revise it.</li><li>Set a check-back date and explain how you will know it helped.</li></ol><p><b>Success check:</b> Can a younger student explain both the right and a safe next step after trying your activity?</p><p>Club members educate and support; adults handle reports, investigations, safety and discipline.</p></section>
    </>}
    <dialog ref={projection} className="rights-projector" onCancel={e=>{e.preventDefault();closeProjector();}} onClose={()=>setProjecting(false)} aria-labelledby="rights-screen-title">{projecting&&<><div className="rights-controls"><button onClick={closeProjector}>Exit teaching screens</button><span>{screen+1} / {rightsScreens.length}</span></div><small>{rightsScreens[screen].time}</small><h2 id="rights-screen-title">{rightsScreens[screen].title}</h2><p>{rightsScreens[screen].text}</p><h3>Try this</h3><p>{rightsScreens[screen].task}</p>{screen===1&&<a href={rightsSources[4].href} target="_blank" rel="noreferrer">Open UNICEF’s children’s rights →</a>}<details key={screen}><summary>Show a model</summary><p>{rightsScreens[screen].model}</p></details><div className="rights-controls"><button disabled={screen===0} onClick={()=>{setScreen(s=>s-1);projection.current?.scrollTo(0,0);}}>← Previous</button><button onClick={()=>{if(screen<rightsScreens.length-1){setScreen(s=>s+1);projection.current?.scrollTo(0,0);}else closeProjector();}}>{screen===rightsScreens.length-1?"Finish":"Next →"}</button><button onClick={()=>{closeProjector();setSection("scenarios");}}>Open scenarios</button></div></>}</dialog>
    <section className="rights-print"><h1>Where Is the Line?</h1><p>Name: ____________________ Date: ______________</p><h2>{active.title}</h2><p>{active.text}</p><p>Read this fictional case. Choose any categories you can support. Categories can overlap; you can change your mind after discussing.</p><p>{rightsLabels.map(l=>`□ ${l}`).join(" · ")}</p>{["What detail supports your thinking?","What else would you need to know?","Whose rights or participation are affected?","What could a student do? What should an adult do?"].map(q=><div key={q}><h3>{q}</h3><div className="rights-writing-space"/></div>)}<p>You may draw, write or explain aloud. We are discussing rights and responses, not deciding criminal guilt.</p></section>
  </section>;
}
