// Canonical rights inquiry content. Mirror with rights-strand.tsx and rights-strand.css into Learn.
export const rightsSources = [
  { label: "Justice Canada · freedom of expression", href: "https://www.justice.gc.ca/eng/csj-sjc/rfc-dlc/ccrf-ccdl/check/art2b.html" },
  { label: "Criminal Code · section 319", href: "https://laws-lois.justice.gc.ca/eng/acts/c-46/section-319.html" },
  { label: "BC Human Rights Code · sections 3, 7 and 8", href: "https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/00_96210_01" },
  { label: "Walnut Road · school code of conduct", href: "https://www.surreyschools.ca/walnutroad/code-of-conduct" },
  { label: "UNICEF · children’s rights explained", href: "https://www.unicef.org/child-rights-convention/convention-text-childrens-version" },
  { label: "Canada · National Child Day", href: "https://www.canada.ca/en/public-health/services/national-child-day.html" },
  { label: "Canada · Human Rights Day", href: "https://www.canada.ca/en/canadian-heritage/services/human-rights-commemorative-days/human-rights-day.html" },
  { label: "BC · Social Studies 6 curriculum", href: "https://curriculum.gov.bc.ca/curriculum/social-studies/6/core" },
];
export const rightsMilestones = [
  { when: "October · introduction", title: "Can I disagree?", detail: "One 25-minute introduction alongside classroom agreements, Freedom, Rules & Power, and evidence work. Practise criticizing a decision while respecting people’s dignity." },
  { when: "November 9–20 · inquiry", title: "Whose rights? Whose responsibility?", detail: "Use two 35-minute sessions within the power-and-rights sequence: Where Is the Line? and a children’s-rights action proposal." },
  { when: "Friday, November 20, 2026", title: "National Child Day / World Children’s Day", detail: "Share a tested scenario or proposal about children’s voice, equal treatment and adult responsibility. This is a learning milestone, not a school closure." },
  { when: "November 23–December 9 · develop", title: "Rights, evidence and fair responses", detail: "Revise one case with source evidence, a response that protects rights, and a question that remains. Build this into the existing Human Rights Day gallery." },
  { when: "Thursday, December 10, 2026", title: "Human Rights Day", detail: "Share the case gallery or a short teach-back. Explain what changed after feedback. Choose one school action to revisit before winter break." },
];
export const rightsTerms = [
  ["Expression", "Sharing meaning through words, art, signs or other communication."],
  ["Prejudice", "Judging a person or group before knowing them, often using a stereotype."],
  ["Racism", "Ideas, actions or systems that disadvantage people because of race or racialized identity. It can be personal or built into rules and routines."],
  ["Discrimination", "Unfair disadvantage connected to who someone is. In law, protected characteristics and the setting matter; intent is not always required."],
  ["Hate speech", "A legal term with a high threshold. A hurtful or racist statement is not automatically a criminal offence. Adults need context and legal guidance."],
];
export const rightsLabels = ["Disagreement / expression", "Racism / prejudice", "Exclusion / discrimination concern", "School conduct concern", "Need more information"];
export const rightsCases = [
  { id: "petition", title: "A petition about recess", text: "Students write a petition asking for a different recess schedule. It criticizes the school’s decision, gives reasons and invites people to sign without pressure.", tags: [0], reason: "Criticizing a decision is a useful form of expression. Disagreement with an adult is not, by itself, racism or misconduct.", missing: "How will students share it without disrupting learning or pressuring others?", action: "Ask for a time to present the reasons and listen to the school’s response." },
  { id: "accent", title: "‘It was only a joke’", text: "In a class discussion, a student copies another student’s accent to make people laugh. The speaker stops contributing. The first student says it was only a joke.", tags: [1,3], reason: "Mocking an accent can reinforce racial or cultural prejudice and make participation unsafe. Calling it a joke does not erase its effect; these facts do not establish a criminal offence.", missing: "What support does the targeted student want, and has this happened before?", action: "Stop the mockery, give the speaker space and ask an adult to help. Do not ask the targeted student to explain a whole culture." },
  { id: "club", title: "A club excludes a faith", text: "A school club advertises that Jewish and Muslim students cannot join, even though the activity has nothing to do with religion.", tags: [1,2,3], reason: "Excluding children because of religion is a discrimination concern. Here it targets Jewish and Muslim students. Adults must address access and safety; a tribunal’s legal finding would require the full facts.", missing: "Who set the rule, who saw it, and what has the school done?", action: "Tell a trusted adult, remove the exclusion and support affected students. Do not hold a class vote on whether they deserve equal rights." },
  { id: "family", title: "A family becomes the punchline", text: "A student repeatedly makes fun of a classmate for having two dads. Other students repeat the joke, even after being asked to stop.", tags: [1,3], reason: "This is homophobic prejudice and a school conduct concern. Everyone’s family deserves dignity. Harm needs attention even when nobody has decided whether a law was broken.", missing: "Who needs support, and what will stop the repetition and retaliation?", action: "Do not join in. If safe, say ‘Families are not a punchline.’ Check in privately and get adult help." },
  { id: "policy", title: "Criticizing a government", text: "A student says a government’s policy is unfair and explains why using a news report. Another student says criticizing that government must mean hating everyone from that country.", tags: [0,4], reason: "Criticism of a government or policy is not automatically prejudice against a people. Examine the actual claim and evidence, and distinguish leaders’ decisions from people’s identities.", missing: "What was said? Did it criticize a policy or generalize about a whole population? Is the report reliable?", action: "Restate the policy claim precisely and compare evidence without blaming classmates or identity groups." },
  { id: "screenshot", title: "A cropped screenshot", text: "A cropped screenshot appears to show a student repeating an insulting stereotype. The words before and after it are missing. Someone wants to post the student’s name publicly.", tags: [4], reason: "The missing context matters: someone might be endorsing a stereotype, quoting it to challenge it, or sharing a manipulated image. Uncertainty does not prevent adults from supporting anyone harmed.", missing: "Is it authentic? What was the full conversation and why was it shared?", action: "Do not repost or name the student publicly. Show a trusted adult and ask them to check the context privately." },
  { id: "threat", title: "A message urges harm", text: "A group-chat message urges others to hurt students because of their race. A classmate sees it and is frightened.", tags: [1,3,4], reason: "This requires urgent adult help. It may involve threats or criminal hate-related conduct. Students do not investigate or decide criminal guilt.", missing: "Adults need to assess immediate safety, the full message and its context. Help should not wait for every fact.", action: "Get a trusted adult immediately. Do not confront the sender or circulate the message. If someone is in immediate danger, seek emergency help." },
  { id: "speech", title: "An unpopular school opinion", text: "A student calmly argues that uniforms should be optional. The teacher disagrees and says the student should lose recess just for expressing that opinion.", tags: [0,4], reason: "Adults also have responsibilities to respect expression and respond fairly. An unpopular opinion alone is not a good reason for punishment. We need the full context of any school response.", missing: "Was there any separate conduct concern, and what explanation was given?", action: "Ask calmly for the reason, seek support from a trusted adult and use the school’s review process." },
  { id: "access", title: "One way to be heard", text: "A class council accepts ideas only from students who stand up and give a fast spoken speech. A student who uses a communication device cannot take part.", tags: [2], reason: "A rule can create an access barrier even when no one intended harm. Equal participation may need different ways to contribute.", missing: "What options would work for the students affected, and who can change the rule?", action: "Offer written, recorded, supported or device-assisted contributions, with enough time. Ask students privately what helps." },
];
export const rightsScreens = [
  { title: "Can I disagree?", time: "Notice · 4 minutes", text: "A student says, ‘The recess schedule should change because some groups have less time to play.’ What is the student criticizing: an idea, a decision or a person’s identity?", task: "Think silently, then share one reason with a partner. You can write, draw, speak or pass.", model: "‘The student is criticizing a schedule. They give a reason that others can discuss.’" },
  { title: "Rights belong to everyone", time: "Learn · 6 minutes", text: "People have a right to express ideas and a right to dignity and equal treatment. Children also have a right to be heard about decisions affecting them. Having a right does not mean always getting your preferred outcome.", task: "Read UNICEF’s child-friendly articles 2, 12 and 13 with your teacher. Name one right and one adult responsibility.", model: "‘Children can share views about a school decision; adults should listen and explain what happens next.’" },
  { title: "An opinion or an attack?", time: "Practise · 10 minutes", text: "Compare: ‘I disagree with this club’s rule because it leaves people out’ and ‘People from that culture should not join our club.’", task: "Explain the difference. Then open Where Is the Line? and discuss the petition and club cases. Categories may overlap.", model: "‘The first challenges a rule. The second excludes people because of identity. I would ask an adult to help change the exclusion.’" },
  { title: "Say it, support it, check it", time: "Finish · 5 minutes", text: "Finish two sentences: ‘People need freedom of expression because…’ and ‘When words exclude or threaten someone, we can…’", task: "Add one example and one question you still have. Hand in your response or explain it to your teacher.", model: "‘We need expression to challenge unfair rules. If someone is targeted, I can support them and get adult help.’" },
];
