"use client";

import { useState } from "react";
import { socialLessons, socialUnits, type PublicSocialLesson } from "./social-public";

export default function SocialStudiesPublic({ audience }: { audience: "student" | "family" }) {
  const [lessonId, setLessonId] = useState<string | null>(null);
  const lesson = socialLessons.find((item) => item.id === lessonId) ?? null;
  if (lesson) return <PublicSocialLessonPage lesson={lesson} onBack={() => setLessonId(null)} />;
  return <main className="content-page public-social-page">
    <section className="page-hero"><p className="eyebrow">SOCIAL STUDIES 6 · GLOBAL ISSUES &amp; GOVERNANCE</p><h1>Question the source. Compare perspectives. Build a case.</h1><p>{audience === "student" ? "You will practise inquiry through local maps, media claims, stakeholder cases, and a Fleetwood evidence file before leading a more independent solutionary inquiry." : "Social Studies teaches the inquiry process in the first half of the year. Families can see student questions, public resources, success criteria, and portfolio expectations; private preparation and internal assessment notes remain in the Teacher Hub."}</p></section>
    <section className="public-social-arc"><div><b>1</b><span><small>NOTICE</small><strong>What does the source show?</strong></span></div><i>→</i><div><b>2</b><span><small>VERIFY</small><strong>What evidence holds up?</strong></span></div><i>→</i><div><b>3</b><span><small>INTERPRET</small><strong>Which perspectives and consequences matter?</strong></span></div><i>→</i><div><b>4</b><span><small>CONTRIBUTE</small><strong>What response is responsible?</strong></span></div></section>
    <section className="public-social-units"><header><p className="eyebrow">FIRST-HALF JOURNEY</p><h2>Four connected units</h2></header><div>{socialUnits.map((unit) => <article key={unit[0]} className={unit[0] === "01" ? "ready" : "planned"}><span>{unit[0]}</span><small>{unit[4]}</small><h3>{unit[1]}</h3><p>{unit[2]}</p><b>{unit[3]}</b></article>)}</div></section>
    <section className="lesson-list public-social-lessons"><header><p className="eyebrow">UNIT 1 · 8–9 CLASS BLOCKS</p><h2>Place, Evidence &amp; Perspective</h2><p>Each lesson combines on-screen tools with maps, source packets, notebooks, discussion, physical creation, and feedback.</p></header>{socialLessons.map((item, index) => <button key={item.id} onClick={() => setLessonId(item.id)}><span>{String(index + 1).padStart(2, "0")}</span><div><small>{item.kind.toUpperCase()} · {item.duration}</small><strong>{item.title}</strong><p>{item.question}</p><i className={`evidence-pill ${item.evidenceLevel.toLowerCase().replaceAll(" ", "-")}`}>{item.evidenceLevel}</i></div><b>OPEN →</b></button>)}</section>
  </main>;
}

function PublicSocialLessonPage({ lesson, onBack }: { lesson: PublicSocialLesson; onBack: () => void }) {
  const [scene, setScene] = useState(0);
  const current = lesson.scenes[scene];
  return <main className="content-page public-social-lesson">
    <button className="back-button" onClick={onBack}>← Back to Social Studies</button>
    <section className="social-public-hero"><div><p>SOCIAL STUDIES 6 · {lesson.kind.toUpperCase()}</p><h1>{lesson.title}</h1><strong>{lesson.question}</strong></div><span>{lesson.duration}</span></section>
    <section className="lesson-goal"><div><small>WE ARE LEARNING</small><p>{lesson.learning}</p></div><div><small>SUCCESS LOOKS LIKE</small>{lesson.success.map((item) => <p key={item}><b>✓</b>{item}</p>)}</div></section>
    <section className={`public-evidence ${lesson.evidenceLevel.toLowerCase().replaceAll(" ", "-")}`}><span>{lesson.evidenceLevel === "Practice" ? "PRACTICE" : lesson.evidenceLevel === "Checkpoint" ? "SPACES EDU CHECKPOINT" : "SPACES EDU PORTFOLIO HIGHLIGHT"}</span><div><strong>{lesson.evidenceSubjects.join(" · ")}</strong><p>{lesson.spacesPrompt}</p></div></section>
    <div className="scene-layout"><nav>{lesson.scenes.map((item, index) => <button key={item.title} className={scene === index ? "selected" : ""} onClick={() => setScene(index)}><span>{index + 1}</span><div><small>{item.label}</small><strong>{item.title}</strong></div></button>)}</nav><article className="scene-card"><header><small>{current.label.toUpperCase()} · {scene + 1} OF {lesson.scenes.length}</small><h2>{current.title}</h2><p>{current.prompt}</p></header><div className="scene-facts"><span><small>TIME</small><strong>{current.time}</strong></span><span><small>HOW WE LEARN</small><strong>{current.learningMode}</strong></span><span><small>WHAT YOU PRODUCE</small><strong>{current.studentTask}</strong></span></div><PublicSocialLab lessonId={lesson.id} scene={scene} />{lesson.resources.length > 0 && <section className="public-resources"><small>LEARN BEYOND THIS SCREEN</small>{lesson.resources.map((resource) => <a key={resource.url} href={resource.url} target="_blank" rel="noreferrer"><span>↗</span><div><small>{resource.gradeFit} · {resource.source}</small><strong>{resource.label}</strong><p><b>Your purpose:</b> {resource.purpose}</p></div><b>OPEN</b></a>)}</section>}<footer><button disabled={scene === 0} onClick={() => setScene(scene - 1)}>← Previous</button><span>{scene + 1} / {lesson.scenes.length}</span><button disabled={scene === lesson.scenes.length - 1} onClick={() => setScene(scene + 1)}>Next →</button></footer></article></div>
    <section className="lesson-close"><article><small>REFLECT</small><p>{lesson.id === "maps-make-arguments" ? "Which map changed what you noticed about place?" : lesson.id === "trace-the-claim" ? "Which verification move changed your judgment most?" : lesson.id === "perspective-without-guessing" ? "What could you responsibly infer—and what remained unknown?" : "Which source complicated your recommendation?"}</p></article><article><small>EXIT</small><p>Point to one specific piece of evidence, explain what it supports, and state one limit.</p></article><article><small>VOCABULARY</small><p>{lesson.vocabulary.join(" · ")}</p></article></section>
  </main>;
}

function PublicSocialLab({ lessonId, scene }: { lessonId: string; scene: number }) {
  const [checks, setChecks] = useState<Record<string, boolean>>({});
  const configs: Record<string, string[][]> = {
    "maps-make-arguments": scene === 0 ? [["Observation", "The map uses a thick blue line beside Fraser Highway."], ["Inference", "The maker thinks transit matters more than parks."], ["Question", "What time period does this map represent?"]] : scene === 1 ? [["Creator", "Who made or published it?"], ["Purpose", "What action is it designed to support?"], ["Visible", "What does the legend make easy to notice?"], ["Missing", "What requires another source?"]] : scene === 2 ? [["Street map", "Routes and named locations"], ["First Peoples’ map", "Languages, communities, and place knowledge"], ["Planning map", "Proposed growth and public decisions"]] : [["Audience", "Who will use this map?"], ["Purpose", "What decision does it support?"], ["Evidence", "Where did the information come from?"], ["Limit", "What important thing is omitted?"]],
    "trace-the-claim": scene === 0 ? [["Emotional pull", "Urgency or outrage pushes a quick reaction."], ["Missing origin", "No original report or data is linked."], ["Context gap", "The image, date, or number may be incomplete."]] : scene === 1 ? [["Check", "Look for an existing fact-check."], ["Find", "Trace the claim to the original."], ["Verify", "Investigate who is behind the source."], ["Compare", "Check independent sources."]] : scene === 2 ? [["Origin", "Original creator and publication date"], ["Evidence", "What the original actually supports"], ["Corroboration", "Independent reporting or data"], ["Context", "What the viral version omitted"]] : [["Supported", "Relevant independent sources agree."], ["Contradicted", "Reliable evidence directly conflicts."], ["Uncertain", "Available evidence cannot settle it yet."]],
    "perspective-without-guessing": scene < 2 ? [["Evidence", "What the person or source actually states"], ["Inference", "A possible priority supported by evidence"], ["Unknown", "What we cannot responsibly claim"]] : [["Benefit", "Who gains access, safety, time, space, or opportunity?"], ["Cost", "Who gives up money, access, time, space, or security?"], ["Missing voice", "Who is affected but not represented?"], ["Revision", "What change could reduce harm?"]],
    "fleetwood-case-file": scene === 0 ? [["Place", "The geographic area is clear."], ["Decision", "The choice or issue is specific."], ["People", "Affected stakeholders are named."], ["Evidence", "Sources exist to investigate it."]] : scene === 1 ? [["Different work", "Each source adds a different kind of evidence."], ["Creator/date", "Source details are recorded."], ["Purpose", "Why it was created is considered."], ["Limit", "A weakness or gap is named."]] : scene === 2 ? [["Short term", "Immediate benefits and costs"], ["Long term", "Possible future consequences"], ["Intended", "What the option is meant to change"], ["Unintended", "What else might happen"]] : [["Claim", "A clear, qualified recommendation"], ["Evidence", "Support from several sources"], ["Perspective", "Affected people represented carefully"], ["Limit", "Uncertainty is visible"], ["Reflection", "Individual thinking and contribution"]],
  };
  const items = configs[lessonId] ?? [];
  const active = items.filter(([label]) => checks[`${lessonId}-${scene}-${label}`]).length;
  return <section className="public-social-lab"><header><small>ON-SCREEN THINKING TOOL</small><h3>{lessonId === "maps-make-arguments" ? "Interrogate the map" : lessonId === "trace-the-claim" ? "Build the evidence trail" : lessonId === "perspective-without-guessing" ? "Separate evidence from assumption" : "Audit the case file"}</h3><p>Use this to plan and discuss. The deeper work happens in your sources, notebook, conversation, and creation.</p></header><div>{items.map(([label, detail]) => { const key = `${lessonId}-${scene}-${label}`; return <button key={key} className={checks[key] ? "checked" : ""} onClick={() => setChecks((current) => ({ ...current, [key]: !current[key] }))}><b>{checks[key] ? "✓" : "?"}</b><span><strong>{label}</strong><small>{detail}</small></span></button>; })}</div><footer><strong>{active} of {items.length} considered</strong><span>Checking a box is not the evidence—be ready to point to the source or reasoning.</span></footer></section>;
}
