import Link from "next/link";
import learning from "../content/truth-learning-2026.json";
import "./truth-family-page.css";

export function TruthLearningLink() {
  return <aside className="truth-learning-link"><strong>Truth, evidence &amp; living Nations</strong><p>Our September learning, source-care card and optional family conversation.</p><Link href="/truth-and-reconciliation">Open the learning page →</Link></aside>;
}

export default function TruthFamilyPage() {
  return <main className="content-page truth-family-page">
    <header><p className="eyebrow">GRADE 6 · STUDENTS &amp; FAMILIES</p><h1>Truth, evidence &amp; living Nations</h1><p>We are learning what residential schools did, how we learn from evidence, and how to act with respect and responsibility today.</p></header>
    <section><h2>What we will learn</h2><p>Canada’s residential-school system separated Indigenous children from their families and cultures. It harmed children, families, languages and Nations. Many children died. Survivors and their families have worked for truth and change.</p><p>First Nations, Inuit and Métis peoples have living cultures, governments and rights. Here in Surrey, we will also learn from public sources shared by Katzie, Semiahmoo and Kwantlen, each a distinct Nation.</p><p><b>Our planned learning:</b> {learning.dates.learning}. We plan to share a learning display on September 29. Orange Shirt Day and the National Day for Truth and Reconciliation are September 30. We will revisit our class responsibility on October 8.</p></section>
    <section><h2>Students: begin with three sources</h2><p>Use the cards with your teacher. A <b>source</b> is where information comes from. <b>Testimony</b> is someone’s account of what they experienced. Read or listen, then name one detail and who shared it.</p>
      {learning.sources.map((source, index) => <details key={source.id}><summary>{index + 1}. {source.title}</summary><p><b>{source.creator}</b> · {source.kind}</p><p><b>Classroom summary:</b> {source.context}</p><blockquote>{source.quote}</blockquote><p><b>Try:</b> {source.question}</p><p>{source.limit}</p><p>{source.date}</p><a href={source.href} target="_blank" rel="noreferrer">Original source — open with an adult ↗</a></details>)}
    </section>
    <section><h2>Your source-care card</h2><p>On paper, in a labelled drawing, through dictation or in a conversation, show:</p><ol><li>The source title and person or Nation that created it.</li><li>One accurate detail and what it helps you understand.</li><li>A question you still have.</li><li>How you will credit and use the source with care.</li><li>One responsibility our class can keep, a helper, and a date to check back.</li></ol><p><b>Example:</b> Katzie describes work to keep its place names spoken. We can credit Katzie when we explain what we learned, and revisit a public Nation-authored source with our teacher on October 8.</p><details><summary>Keep this source-care reminder</summary><ul>{learning.care.map(item => <li key={item}>{item}</li>)}</ul></details><p><b>Check:</b> can you point to your detail in its source and name something a Nation is continuing today?</p></section>
    <section><h2>For families</h2><p>The class will use short, selected passages from Phyllis Webstad, NCTR and Katzie First Nation. Phyllis’s story is her own; we will not treat it as every Survivor’s experience. Full linked pages can contain more difficult material than the selected cards, so please preview them before opening them with your child.</p><p>Students may listen quietly, draw, dictate or talk with a partner. They may pass on speaking and ask for a pause. There are no trauma simulations, debates about documented harms, or requests to share family experiences. Indigenous students are not expected to speak for a Nation. Please contact Mr. Wyatt privately if your child needs support.</p><h3>Optional conversation at home</h3><ul><li>Who shared something you learned, and how did you credit them?</li><li>What did you learn about a Nation’s life, language or work today?</li><li>What responsibility did the class choose? How will you know it followed through?</li></ul><p>This conversation is optional, not a homework submission. Your child can choose what to share.</p></section>
    <section><h2>Learn from the original sources</h2><ul>{learning.links.map(link => <li key={link.href}><a href={link.href} target="_blank" rel="noreferrer">{link.label} ↗</a></li>)}</ul><p>The cards are classroom selections with summaries and short quotations. They do not replace the complete sources or ongoing learning with Indigenous communities.</p></section>
    <Link href="/families">← Families</Link> · <Link href="/students">Students →</Link>
  </main>;
}
